# Use the official nginx base image
FROM nginx:alpine

# Copy custom nginx config
COPY nginx.conf /etc/nginx/nginx.conf

# Copy HTML file into the nginx default HTML directory
COPY index.html /usr/share/nginx/html/index.html
